SELECT *
FROM TABS;

CREATE TABLE TESTERMODEL_0310
(NAME VARCHAR2(30),
BIRTH INT
);

INSERT INTO TESTERMODEL_0310
(NAME, BIRTH)
VALUES
('백',11110101);

SELECT *
FROM TESTERMODEL_0310;

CREATE TABLE TESTERMODEL_0310_2(
REGIONID VARCHAR2(100),
PRODUCT VARCHAR2(100),
YEARWEEK VARCHAR2(100),
QTY NUMBER,
constraints PK_TESTERMODEL_0310_2 primary key (REGIONID, PRODUCT,YEARWEEK)
);

INSERT INTO TESTERMODEL_0310_2
VALUES('A01','PRODUCT01','202301',100);

SELECT * 
FROM TESTERMODEL_0310_2;

-- 부모테이블 생성
 CREATE TABLE KOPO_EVENT_INFO_FOREIGN(
     EVENTID VARCHAR2(20),
     EVENTPERIOD VARCHAR2(20),
     PROMOTION_RATIO NUMBER,
 constraint pk_kopo_event_info_foreign primary key(EVENTID));

-- 자식테이블 생성
 CREATE TABLE KOPO_PRODUCT_VOLUME_FOREIGN(
     REGIONID VARCHAR2(20),
     PRODUCTGROUP VARCHAR2(20),
     YEARWEEK VARCHAR2(8),
     VOLUME NUMBER NOT NULL,
     EVENTID VARCHAR2(20),
 constraint pk_kopo_product_volume_foreign primary key(REGIONID, PRODUCTGROUP, YEARWEEK),
 constraint fk_kopo_product_volume_foreign foreign key(eventid) references KOPO_EVENT_INFO_FOREIGN(EVENTID) );
 
 SELECT *
 FROM KOPO_PRODUCT_VOLUME_FOREIGN;
 
