-- 부모테이블 생성
 CREATE TABLE KOPO_EVENT_INFO_FOREIGN(
     EVENTID VARCHAR2(20),
     EVENTPERIOD VARCHAR2(20),
     PROMOTION_RATIO NUMBER,
 constraint pk_kopo_event_info_foreign primary key(EVENTID));

-- 자식테이블 생성
CREATE TABLE KOPO_PRODUCT_VOLUME_FOREIGN(
    REGIONID VARCHAR2(20),
    PRODUCTGROUP VARCHAR2(20),
    YEARWEEK VARCHAR2(8),
    VOLUME NUMBER NOT NULL,
    EVENTID VARCHAR2(20),
constraint pk_kopo_product_volume_foreign primary key(REGIONID, PRODUCTGROUP, YEARWEEK),
constraint fk_kopo_product_volume_foreign foreign key(eventid) references KOPO_EVENT_INFO_FOREIGN(EVENTID) );
 

INSERT INTO KOPO_EVENT_INFO_FOREIGN
VALUES('EV001','30',0.3);

INSERT INTO KOPO_PRODUCT_VOLUME_FOREIGN 
VALUES ('A01','PRD001','202301',1000,'EV001');

SELECT *
FROM KOPO_EVENT_INFO_FOREIGN;
 
SELECT *
FROM KOPO_PRODUCT_VOLUME_FOREIGN;

DELETE KOPO_EVENT_INFO_FOREIGN
WHERE EVENTID = 'EV001';

DELETE KOPO_PRODUCT_VOLUME_FOREIGN
WHERE EVENTID = 'EV001';
-- 첫번째 자식 테이블에는 있는데 부모 테이블에서 데이터를 삭제한다
-- 넣을때는 부모 -> 자식 , 삭제는 자식 -> 부모 순서로

 
--두번째 