DROP TABLE TESTER3;

DROP TABLE TESTER_SON3;

SELECT * FROM TABS;

-- 부모테이블 생성
CREATE TABLE TESTER3 (
REGION VARCHAR2(100),
NAME VARCHAR2(20),
constraint pk_TESTER3 primary key(NAME)
);

SELECT * FROM TESTER3;

INSERT INTO TESTER3
(REGION, NAME)
VALUES
('서울시','백승수');

-- 자식테이블 생성
CREATE TABLE TESTER_SON3(
REGION VARCHAR2(100),
NAME VARCHAR2(20),
BIRTH NUMBER,
JOB VARCHAR2(10),
constraint pk_TESTER_SON3 primary key(NAME, BIRTH, JOB),
constraint fk_TESTER_SON3 foreign key(NAME) references TESTER3(NAME) 
);

SELECT * FROM TESTER_SON3;